# Generated by Django 5.2.8 on 2025-12-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
